INSERT INTO GENERO_ENTITY (NOMBRE) VALUES ('ROCK');
INSERT INTO GENERO_ENTITY (NOMBRE) VALUES ('HEAVY METAL');
INSERT INTO GENERO_ENTITY (NOMBRE) VALUES ('JAZZ');
INSERT INTO GENERO_ENTITY (NOMBRE) VALUES ('POP');

INSERT INTO ARTISTA_ENTITY (NOMBRE) VALUES ('MICHAEL JACKSON');
INSERT INTO ARTISTA_ENTITY (NOMBRE) VALUES ('METALLICA');
INSERT INTO ARTISTA_ENTITY (NOMBRE) VALUES ('LED ZEPPELIN');

INSERT INTO ALBUM_ENTITY (FECHA_SALIDA, NOMBRE, ID_ARTISTA, GENERO_ID_GENERO) VALUES ('1991-11-26', 'DANGEROUS', 1, 1);
INSERT INTO ALBUM_ENTITY (FECHA_SALIDA, NOMBRE, ID_ARTISTA, GENERO_ID_GENERO) VALUES ('1987-08-31', 'BAD', 1, 4);
INSERT INTO ALBUM_ENTITY (FECHA_SALIDA, NOMBRE, ID_ARTISTA, GENERO_ID_GENERO) VALUES ('1986-03-03', 'MASTER OF PUPPETS', 2, 2);
INSERT INTO ALBUM_ENTITY (FECHA_SALIDA, NOMBRE, ID_ARTISTA, GENERO_ID_GENERO) VALUES ('1971-11-04', 'LED ZEPPELIN IV', 3, 2);
